// <auto-generated />
using System;
using Funds.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Funds.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Funds.Api.Models.Client", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nome");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<decimal>("SaldoDisponivel")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_disponivel");

                    b.HasKey("IdCliente");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Funds.Api.Models.ClientPosition", b =>
                {
                    b.Property<int>("IdPosicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_posicao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPosicao"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("criado_em");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdFundo")
                        .HasColumnType("int")
                        .HasColumnName("id_fundo");

                    b.Property<int>("QuantidadeCotas")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_cotas");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("IdPosicao");

                    b.HasIndex("IdCliente", "IdFundo")
                        .IsUnique();

                    b.ToTable("posicoes_clientes", (string)null);
                });

            modelBuilder.Entity("Funds.Api.Models.Fund", b =>
                {
                    b.Property<int>("IdFundo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_fundo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFundo"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("criado_em");

                    b.Property<TimeSpan>("HorarioCorte")
                        .HasColumnType("time")
                        .HasColumnName("horario_corte");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nome");

                    b.Property<string>("StatusCaptacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_captacao");

                    b.Property<decimal>("ValorCota")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("valor_cota");

                    b.Property<decimal>("ValorMinimoAporte")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_minimo_aporte");

                    b.Property<decimal>("ValorMinimoPermanencia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_minimo_permanencia");

                    b.HasKey("IdFundo");

                    b.ToTable("fundos", (string)null);
                });

            modelBuilder.Entity("Funds.Api.Models.Order", b =>
                {
                    b.Property<long>("IdOrdem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_ordem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdOrdem"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataAgendamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_agendamento");

                    b.Property<DateTime?>("ExecutadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("executado_em");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdFundo")
                        .HasColumnType("int")
                        .HasColumnName("id_fundo");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("motivo_rejeicao");

                    b.Property<int>("QuantidadeCotas")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_cotas");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TipoExecucao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_execucao");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_operacao");

                    b.Property<decimal>("ValorCota")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("valor_cota");

                    b.Property<decimal>("ValorOperacao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_operacao");

                    b.HasKey("IdOrdem");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[idempotency_key] IS NOT NULL");

                    b.ToTable("ordens", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
